# Generated by Django 6.0.7 on 2026-07-20 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('generic_name', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=100)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('batch_number', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Cream', 'Cream'), ('Drops', 'Drops'), ('Ointment', 'Ointment'), ('Other', 'Other')], max_length=20)),
                ('unit', models.CharField(choices=[('Box', 'Box'), ('Bottle', 'Bottle'), ('Strip', 'Strip'), ('Tube', 'Tube'), ('Vial', 'Vial'), ('Piece', 'Piece')], max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_stock', models.PositiveIntegerField(default=0)),
                ('minimum_stock', models.PositiveIntegerField(default=10)),
                ('expiry_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drugs', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Drug',
                'verbose_name_plural': 'Drugs',
                'ordering': ['name'],
            },
        ),
    ]
